title: optozorax blog
description: Мои программульки и результаты их работы.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://optozorax.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%d %b %Y"

theme: # leave it empty

# social
author: "optozorax"
image: /thumbnail.png
github:
  owner_url: https://github.com/optozorax
  owner_name: optozorax
twitter:
  username: optozorax
vk:
  group: optoblog
  user: optozorax
klavogonki:
  user: 517589
tg:
  channel: zoraxblog
  user: zorax


plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow